# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QStatusBar, QTextBrowser,
    QWidget)
import sjtu_rc

class Ui_IncoiceDetectorUI(object):
    def setupUi(self, IncoiceDetectorUI):
        if not IncoiceDetectorUI.objectName():
            IncoiceDetectorUI.setObjectName(u"IncoiceDetectorUI")
        IncoiceDetectorUI.resize(800, 600)
        icon = QIcon()
        icon.addFile(u"logo.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        IncoiceDetectorUI.setWindowIcon(icon)
        IncoiceDetectorUI.setAutoFillBackground(False)
        self.actionVersion2_0_qt = QAction(IncoiceDetectorUI)
        self.actionVersion2_0_qt.setObjectName(u"actionVersion2_0_qt")
        self.actionDocumentation = QAction(IncoiceDetectorUI)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.centralwidget = QWidget(IncoiceDetectorUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_Workspace = QFrame(self.centralwidget)
        self.frame_Workspace.setObjectName(u"frame_Workspace")
        self.frame_Workspace.setGeometry(QRect(0, 70, 421, 231))
        self.frame_Workspace.setFrameShape(QFrame.StyledPanel)
        self.frame_Workspace.setFrameShadow(QFrame.Raised)
        self.pushButton_choose_file = QPushButton(self.frame_Workspace)
        self.pushButton_choose_file.setObjectName(u"pushButton_choose_file")
        self.pushButton_choose_file.setGeometry(QRect(60, 40, 141, 31))
        self.pushButton_choose_file.setStyleSheet(u"background-image: undefined;")
        self.pushButton_choose_Folder = QPushButton(self.frame_Workspace)
        self.pushButton_choose_Folder.setObjectName(u"pushButton_choose_Folder")
        self.pushButton_choose_Folder.setGeometry(QRect(240, 40, 141, 31))
        self.label_2 = QLabel(self.frame_Workspace)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(160, 10, 121, 21))
        self.label_2.setStyleSheet(u"font: 16pt \"Consolas\";")
        self.textBrowser = QTextBrowser(self.frame_Workspace)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(60, 80, 221, 51))
        self.pushButton_Detect = QPushButton(self.frame_Workspace)
        self.pushButton_Detect.setObjectName(u"pushButton_Detect")
        self.pushButton_Detect.setGeometry(QRect(290, 80, 81, 51))
        self.progressBar = QProgressBar(self.frame_Workspace)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(60, 140, 341, 23))
        self.progressBar.setMinimum(-1)
        self.progressBar.setMaximum(0)
        self.progressBar.setValue(-1)
        self.line = QFrame(self.frame_Workspace)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 230, 411, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.result_label = QLabel(self.frame_Workspace)
        self.result_label.setObjectName(u"result_label")
        self.result_label.setGeometry(QRect(60, 170, 301, 61))
        font = QFont()
        font.setFamilies([u"Consolas"])
        self.result_label.setFont(font)
        self.result_label.setStyleSheet(u"color: rgb(245, 0, 0);")
        self.frame_Title = QFrame(self.centralwidget)
        self.frame_Title.setObjectName(u"frame_Title")
        self.frame_Title.setGeometry(QRect(0, -10, 791, 81))
        self.frame_Title.setAcceptDrops(False)
        self.frame_Title.setAutoFillBackground(False)
        self.frame_Title.setFrameShape(QFrame.StyledPanel)
        self.frame_Title.setFrameShadow(QFrame.Raised)
        self.label_logo = QLabel(self.frame_Title)
        self.label_logo.setObjectName(u"label_logo")
        self.label_logo.setGeometry(QRect(20, 10, 51, 51))
        self.label_logo.setStyleSheet(u"image: url(\u6821\u6807-\u6821\u5fbd.png);")
        self.label_logo.setTextFormat(Qt.AutoText)
        self.label_logo.setPixmap(QPixmap(u":/images/InvoiceDetector2.0/png/test/\u6821\u6807-\u6821\u5fbd.png"))
        self.label_logo.setScaledContents(True)
        self.line_title = QFrame(self.frame_Title)
        self.line_title.setObjectName(u"line_title")
        self.line_title.setGeometry(QRect(80, 50, 281, 16))
        self.line_title.setFrameShape(QFrame.Shape.HLine)
        self.line_title.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_co = QLabel(self.frame_Title)
        self.label_co.setObjectName(u"label_co")
        self.label_co.setGeometry(QRect(80, 40, 171, 16))
        self.label_co.setStyleSheet(u"font: italic 9pt \"Carlito\";")
        self.label = QLabel(self.frame_Title)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 791, 81))
        self.label.setPixmap(QPixmap(u"TrueSunset.png"))
        self.label_3 = QLabel(self.frame_Title)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 20, 231, 20))
        self.label_3.setStyleSheet(u"font: 290 16pt \"Microsoft YaHei\";")
        self.label.raise_()
        self.label_logo.raise_()
        self.line_title.raise_()
        self.label_co.raise_()
        self.label_3.raise_()
        self.frame_Searching = QFrame(self.centralwidget)
        self.frame_Searching.setObjectName(u"frame_Searching")
        self.frame_Searching.setGeometry(QRect(0, 300, 421, 141))
        self.frame_Searching.setFrameShape(QFrame.StyledPanel)
        self.frame_Searching.setFrameShadow(QFrame.Raised)
        self.label_Searching = QLabel(self.frame_Searching)
        self.label_Searching.setObjectName(u"label_Searching")
        self.label_Searching.setGeometry(QRect(160, 0, 121, 31))
        self.label_Searching.setStyleSheet(u"font: 16pt \"Consolas\";")
        self.label_invoice_code = QLabel(self.frame_Searching)
        self.label_invoice_code.setObjectName(u"label_invoice_code")
        self.label_invoice_code.setGeometry(QRect(40, 30, 81, 21))
        self.label_invoice_code.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.lineEdit = QLineEdit(self.frame_Searching)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(120, 30, 221, 21))
        self.textBrowser_invoice_info = QTextBrowser(self.frame_Searching)
        self.textBrowser_invoice_info.setObjectName(u"textBrowser_invoice_info")
        self.textBrowser_invoice_info.setGeometry(QRect(40, 60, 371, 31))
        self.pushButton_search = QPushButton(self.frame_Searching)
        self.pushButton_search.setObjectName(u"pushButton_search")
        self.pushButton_search.setGeometry(QRect(350, 30, 61, 23))
        self.pushButton_mod = QPushButton(self.frame_Searching)
        self.pushButton_mod.setObjectName(u"pushButton_mod")
        self.pushButton_mod.setGeometry(QRect(160, 100, 121, 31))
        self.pushButton_del = QPushButton(self.frame_Searching)
        self.pushButton_del.setObjectName(u"pushButton_del")
        self.pushButton_del.setGeometry(QRect(290, 100, 121, 31))
        self.pushButton_add = QPushButton(self.frame_Searching)
        self.pushButton_add.setObjectName(u"pushButton_add")
        self.pushButton_add.setGeometry(QRect(40, 100, 111, 31))
        self.frame_INFO = QFrame(self.centralwidget)
        self.frame_INFO.setObjectName(u"frame_INFO")
        self.frame_INFO.setGeometry(QRect(420, 70, 381, 371))
        self.frame_INFO.setFrameShape(QFrame.StyledPanel)
        self.frame_INFO.setFrameShadow(QFrame.Raised)
        self.line_2 = QFrame(self.frame_INFO)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 0, 20, 371))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.textBrowser_invoicecode = QTextBrowser(self.frame_INFO)
        self.textBrowser_invoicecode.setObjectName(u"textBrowser_invoicecode")
        self.textBrowser_invoicecode.setGeometry(QRect(100, 30, 251, 31))
        self.textBrowser_date = QTextBrowser(self.frame_INFO)
        self.textBrowser_date.setObjectName(u"textBrowser_date")
        self.textBrowser_date.setGeometry(QRect(100, 70, 251, 31))
        self.textBrowser_buyername = QTextBrowser(self.frame_INFO)
        self.textBrowser_buyername.setObjectName(u"textBrowser_buyername")
        self.textBrowser_buyername.setGeometry(QRect(100, 110, 251, 31))
        self.textBrowser_buyercode = QTextBrowser(self.frame_INFO)
        self.textBrowser_buyercode.setObjectName(u"textBrowser_buyercode")
        self.textBrowser_buyercode.setGeometry(QRect(100, 150, 251, 31))
        self.textBrowser_sellername = QTextBrowser(self.frame_INFO)
        self.textBrowser_sellername.setObjectName(u"textBrowser_sellername")
        self.textBrowser_sellername.setGeometry(QRect(100, 190, 251, 31))
        self.textBrowser_sellercode = QTextBrowser(self.frame_INFO)
        self.textBrowser_sellercode.setObjectName(u"textBrowser_sellercode")
        self.textBrowser_sellercode.setGeometry(QRect(100, 230, 251, 31))
        self.textBrowser_totalprice = QTextBrowser(self.frame_INFO)
        self.textBrowser_totalprice.setObjectName(u"textBrowser_totalprice")
        self.textBrowser_totalprice.setGeometry(QRect(100, 270, 251, 31))
        self.label_invoice_code_2 = QLabel(self.frame_INFO)
        self.label_invoice_code_2.setObjectName(u"label_invoice_code_2")
        self.label_invoice_code_2.setGeometry(QRect(20, 30, 81, 21))
        self.label_invoice_code_2.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_Searching_2 = QLabel(self.frame_INFO)
        self.label_Searching_2.setObjectName(u"label_Searching_2")
        self.label_Searching_2.setGeometry(QRect(100, 0, 221, 31))
        self.label_Searching_2.setStyleSheet(u"font: 16pt \"Consolas\";")
        self.label_invoice_date = QLabel(self.frame_INFO)
        self.label_invoice_date.setObjectName(u"label_invoice_date")
        self.label_invoice_date.setGeometry(QRect(20, 70, 81, 21))
        self.label_invoice_date.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_buyername = QLabel(self.frame_INFO)
        self.label_invoice_buyername.setObjectName(u"label_invoice_buyername")
        self.label_invoice_buyername.setGeometry(QRect(20, 110, 81, 21))
        self.label_invoice_buyername.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_buyercode = QLabel(self.frame_INFO)
        self.label_invoice_buyercode.setObjectName(u"label_invoice_buyercode")
        self.label_invoice_buyercode.setGeometry(QRect(20, 150, 81, 21))
        self.label_invoice_buyercode.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_sellername = QLabel(self.frame_INFO)
        self.label_invoice_sellername.setObjectName(u"label_invoice_sellername")
        self.label_invoice_sellername.setGeometry(QRect(20, 190, 81, 21))
        self.label_invoice_sellername.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_sellercode = QLabel(self.frame_INFO)
        self.label_invoice_sellercode.setObjectName(u"label_invoice_sellercode")
        self.label_invoice_sellercode.setGeometry(QRect(20, 230, 81, 21))
        self.label_invoice_sellercode.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_totalprice = QLabel(self.frame_INFO)
        self.label_invoice_totalprice.setObjectName(u"label_invoice_totalprice")
        self.label_invoice_totalprice.setGeometry(QRect(20, 270, 81, 21))
        self.label_invoice_totalprice.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.label_invoice_notes = QLabel(self.frame_INFO)
        self.label_invoice_notes.setObjectName(u"label_invoice_notes")
        self.label_invoice_notes.setGeometry(QRect(20, 310, 81, 21))
        self.label_invoice_notes.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        self.textBrowser_notes = QTextBrowser(self.frame_INFO)
        self.textBrowser_notes.setObjectName(u"textBrowser_notes")
        self.textBrowser_notes.setGeometry(QRect(100, 310, 251, 61))
        self.frame_PIC = QFrame(self.centralwidget)
        self.frame_PIC.setObjectName(u"frame_PIC")
        self.frame_PIC.setGeometry(QRect(0, 440, 611, 111))
        self.frame_PIC.setStyleSheet(u"border-image: url(BG.png);")
        self.frame_PIC.setFrameShape(QFrame.StyledPanel)
        self.frame_PIC.setFrameShadow(QFrame.Raised)
        self.frame_Author = QFrame(self.centralwidget)
        self.frame_Author.setObjectName(u"frame_Author")
        self.frame_Author.setGeometry(QRect(610, 440, 181, 111))
        self.frame_Author.setFrameShape(QFrame.StyledPanel)
        self.frame_Author.setFrameShadow(QFrame.Raised)
        self.label_De = QLabel(self.frame_Author)
        self.label_De.setObjectName(u"label_De")
        self.label_De.setGeometry(QRect(60, 50, 81, 16))
        self.label_De.setStyleSheet(u"font: italic 10pt \"Carlito\";")
        self.label_Name = QLabel(self.frame_Author)
        self.label_Name.setObjectName(u"label_Name")
        self.label_Name.setGeometry(QRect(30, 70, 141, 20))
        self.label_Name.setStyleSheet(u"font: italic 10pt \"Carlito\";")
        self.label_Copy = QLabel(self.frame_Author)
        self.label_Copy.setObjectName(u"label_Copy")
        self.label_Copy.setGeometry(QRect(20, 90, 151, 20))
        self.label_Copy.setStyleSheet(u"font: italic 9pt \"Carlito\";")
        self.label_JAKA = QLabel(self.frame_Author)
        self.label_JAKA.setObjectName(u"label_JAKA")
        self.label_JAKA.setGeometry(QRect(60, 20, 71, 31))
        self.label_JAKA.setStyleSheet(u"border-image: url(logo.png);")
        IncoiceDetectorUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(IncoiceDetectorUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_H = QMenu(self.menubar)
        self.menu_H.setObjectName(u"menu_H")
        IncoiceDetectorUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(IncoiceDetectorUI)
        self.statusbar.setObjectName(u"statusbar")
        IncoiceDetectorUI.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menu.addAction(self.actionVersion2_0_qt)
        self.menu_H.addAction(self.actionDocumentation)

        self.retranslateUi(IncoiceDetectorUI)

        QMetaObject.connectSlotsByName(IncoiceDetectorUI)
    # setupUi

    def retranslateUi(self, IncoiceDetectorUI):
        IncoiceDetectorUI.setWindowTitle(QCoreApplication.translate("IncoiceDetectorUI", u"InvoiceDetect", None))
        self.actionVersion2_0_qt.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Version2.0 (qt)", None))
        self.actionDocumentation.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Documentation", None))
        self.pushButton_choose_file.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Login", None))
        self.pushButton_choose_Folder.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Choose Folder", None))
        self.label_2.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Workspace", None))
        self.pushButton_Detect.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Detect", None))
        self.result_label.setText("")
        self.label_logo.setText("")
        self.label_co.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Created by JAKA,Co,2024", None))
        self.label.setText("")
        self.label_3.setText(QCoreApplication.translate("IncoiceDetectorUI", u"InvoiceDetector 2.1", None))
        self.label_Searching.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Opearting", None))
        self.label_invoice_code.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u53d1\u7968\u4ee3\u7801\uff1a", None))
        self.pushButton_search.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Search", None))
        self.pushButton_mod.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Modify", None))
        self.pushButton_del.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Delete", None))
        self.pushButton_add.setText(QCoreApplication.translate("IncoiceDetectorUI", u"New", None))
        self.label_invoice_code_2.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u53d1\u7968\u4ee3\u7801\uff1a", None))
        self.label_Searching_2.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Searching Results", None))
        self.label_invoice_date.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u5f00\u7968\u65e5\u671f\uff1a", None))
        self.label_invoice_buyername.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u8d2d\u65b9\u540d\u79f0\uff1a", None))
        self.label_invoice_buyercode.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u8d2d\u65b9\u7f16\u53f7\uff1a", None))
        self.label_invoice_sellername.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u9500\u65b9\u540d\u79f0\uff1a", None))
        self.label_invoice_sellercode.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u9500\u65b9\u7f16\u53f7\uff1a", None))
        self.label_invoice_totalprice.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u4ef7\u7a0e\u5408\u8ba1\uff1a", None))
        self.label_invoice_notes.setText(QCoreApplication.translate("IncoiceDetectorUI", u"\u5907\u6ce8\uff1a", None))
        self.label_De.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Designed by", None))
        self.label_Name.setText(QCoreApplication.translate("IncoiceDetectorUI", u"Racheus Zhao,Shuo Qi,", None))
        self.label_Copy.setText(QCoreApplication.translate("IncoiceDetectorUI", u"JAKA Intern.CopyRight\u00a92024", None))
        self.label_JAKA.setText("")
        self.menu.setTitle(QCoreApplication.translate("IncoiceDetectorUI", u"\u7248\u672c(V)", None))
        self.menu_H.setTitle(QCoreApplication.translate("IncoiceDetectorUI", u"\u5e2e\u52a9(H)", None))
    # retranslateUi

