# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\InvoiceDetector2.0\errorlist.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorList(object):
    def setupUi(self, ErrorList):
        ErrorList.setObjectName("ErrorList")
        ErrorList.resize(400, 330)
        self.Errorlabel = QtWidgets.QLabel(parent=ErrorList)
        self.Errorlabel.setGeometry(QtCore.QRect(30, 20, 171, 31))
        self.Errorlabel.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"黑体\";")
        self.Errorlabel.setObjectName("Errorlabel")
        self.textBrowser = QtWidgets.QTextBrowser(parent=ErrorList)
        self.textBrowser.setGeometry(QtCore.QRect(30, 50, 351, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(parent=ErrorList)
        self.pushButton.setGeometry(QtCore.QRect(150, 290, 121, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ErrorList)
        QtCore.QMetaObject.connectSlotsByName(ErrorList)

    def retranslateUi(self, ErrorList):
        _translate = QtCore.QCoreApplication.translate
        ErrorList.setWindowTitle(_translate("ErrorList", "ErrorList"))
        self.Errorlabel.setText(_translate("ErrorList", "未被检测成功的发票："))
        self.pushButton.setText(_translate("ErrorList", "我要“手动录入”"))
