# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\InvoiceDetector2.0\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(390, 247)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Login)
        self.buttonBox.setGeometry(QtCore.QRect(20, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(40, 100, 71, 31))
        self.label.setStyleSheet("font: 11pt \"黑体\";")
        self.label.setObjectName("label")
        self.label_pswd = QtWidgets.QLabel(parent=Login)
        self.label_pswd.setGeometry(QtCore.QRect(40, 140, 71, 31))
        self.label_pswd.setStyleSheet("font: 11pt \"黑体\";")
        self.label_pswd.setObjectName("label_pswd")
        self.lineEdit_account = QtWidgets.QLineEdit(parent=Login)
        self.lineEdit_account.setGeometry(QtCore.QRect(120, 100, 231, 31))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Login)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 140, 231, 31))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_2 = QtWidgets.QLabel(parent=Login)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 81, 41))
        self.label_2.setStyleSheet("font: 700 18pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_pic = QtWidgets.QLabel(parent=Login)
        self.label_pic.setGeometry(QtCore.QRect(80, 20, 71, 61))
        self.label_pic.setText("")
        self.label_pic.setPixmap(QtGui.QPixmap("校标-校徽.png"))
        self.label_pic.setObjectName("label_pic")

        self.retranslateUi(Login)
        self.buttonBox.accepted.connect(Login.accept) # type: ignore
        self.buttonBox.rejected.connect(Login.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "账户名称："))
        self.label_pswd.setText(_translate("Login", "密    码："))
        self.label_2.setText(_translate("Login", "请登录"))
